params:
  seed: 5
  algo:
    name: a2c_continuous

  model:
    name: continuous_a2c_logstd

  network:
    name: actor_critic
    separate: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0
        fixed_sigma: True
    mlp:
      units: [256, 128, 64]
      activation: elu
      initializer:
        name: default
    rnn:
      name: 'lstm'
      units: 400
      layers: 2
      before_mlp: True
    ckpt_path: "/home/mdalal/research/assembly/assembly/trained_models/bc_rnn_furniture_table_sawyer_state_gmm_False_v1/20221112232836/models/model_epoch_5500_sawyer_gen_success_0.9.pth"

  config:
    name: IKEASawyerGen-v0
    env_name: IKEASawyerGen-v0
    score_to_win: 20000000
    normalize_input: False
    normalize_value: True
    value_bootstrap: True
    reward_shaper:
      scale_value: 0.00001
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95

    learning_rate: 5e-4
    lr_schedule: null
    kl_threshold: 0.016
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: True
    e_clip: 0.2
    max_epochs: 2000
    num_actors: 10
    horizon_length: 1000
    seq_length: 10
    minibatch_size: 10000
    mini_epochs: 4
    critic_coef: 2
    clip_value: True
    use_smooth_clamp: True
    bound_loss_type: regularisation
    bounds_loss_coef: 0.0

    env_config:
      config_path: "/home/mdalal/research/assembly/robomimic/robomimic/exps/furniture/table/low_dim/bc_rnn.json"
      seed: 0

    player:
      render: False
      deterministic: True
      games_num: 5
